### ISSUE TITLE
建议在V2RAY的启动日志中加入编译日期

### ISSUE THREAD

**Issue by ToutyRater** [v2fly/discussion#1]
虽然说有版本号，但现在一个问题是 [V2FlyBleedingEdgeBinary](https://github.com/v2fly/V2FlyBleedingEdgeBinary) 发布的非正式版的是跟最新的正式版版本号是一致的，更新多个版本后容易记不住目前使用的是哪个版本

**Comment by kslr** [comment]
这会破坏掉可复制编译，我建议你放到特定的目录测试
