### ISSUE TITLE
求助：服务器端升级报Failed to extract V2Ray（服务器是Debian 4.9.168，V2Ray版本号4.22.1）

### ISSUE THREAD

**Issue by caotg9360** [v2fly/discussion#102]
服务器是Debian 4.9.168，V2Ray版本号4.22.1，今天准备升级新版本
输入：sudo bash go.sh  准备升级更新的，结果最后报
提示：Failed to extract V2Ray.
是我的方法不对吗，请教如何解决，具体提示如下

Installing V2Ray vhttps://api.github.com/repos/v2ray/v2ray-core/releases/32407121 on x86_64
Downloading V2Ray: https://github.com/v2ray/v2ray-core/releases/download/vhttps://api.github.com/repos/v2ray/v2ray-core/releases/32407121/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     32      0 --:--:-- --:--:-- --:--:--    32
Extracting V2Ray package to /tmp/v2ray.
Archive:  /tmp/v2ray/v2ray.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/v2ray/v2ray.zip or
        /tmp/v2ray/v2ray.zip.zip, and cannot find /tmp/v2ray/v2ray.zip.ZIP, period.
Failed to extract V2Ray.

**Comment by kslr** [comment]
go.sh 请自行解决

**Comment by caotg9360** [comment]
> go.sh 请自行解决

实在不好意思，可不可以稍微详细说一下，没有这方面基础知识，之前都是照着教程一步一步做的，感谢

**Comment by hnliuzesen** [comment]
备份一下配置文件，然后用 go.sh 把当前版本卸载了，用这个脚本装一下试试 [https://github.com/v2fly/fhs-install-v2ray](https://github.com/v2fly/fhs-install-v2ray)

**Comment by caotg9360** [comment]
> 备份一下配置文件，然后用 go.sh 把当前版本卸载了，用这个脚本装一下试试 https://github.com/v2fly/fhs-install-v2ray

感谢，终于找到原因啦

**Comment by caotg9360** [comment]
已解决
