### ISSUE TITLE
用了V2RAY IE网站打开报错 这可能是因为该站点使用过期的或不安全的 TLS 安全设置

### ISSUE THREAD

**Issue by vipwuping** [v2fly/discussion#12]
没有V2RAY之前 IE打开可以访问网站 ，用了V2RAY IE打开会报错，  网站是HTTPS  支持TLS1.0  报错内容如果

无法安全地连接到此页面

这可能是因为该站点使用过期的或不安全的 TLS 安全设置。如果这种情况持续发生，请与网站的所有者联系。

TLS 安全设置未设置为默认设置，这也可能导致此错误。

尝试此操作：
我用IE本地网络可以正常打开，这些HTTPS网站的，连接上V2RAY就是不行了。是我哪里设置出错了，还是新版本V2RAY 不支持TLS1.0 导致这些网站打不开呢  这些网站同时也支持  TLS 1.1  1.2 在 WIN10 IE上面就不行 在谷歌浏览器上面确可以打开
就是在V2RAY全局模式下打不开这些网站

**Comment by okudayukiko** [comment]
用Privoxy將SOCKS5轉換為HTTP
或者用Firefox

**Comment by kslr** [comment]
你可以在 ie 禁止 tls1.0
