### ISSUE TITLE
v2fly android二次打包木马？

### ISSUE THREAD

**Issue by zz5678** [v2fly/discussion#13]
https://www.virustotal.com/gui/file/090a9f47705fe00b60a7659ce926462943be2608e616359410fa0a3306646da4/detection
```
MD5	372335fc752ee6f45be46e36eb0e813f
SHA-1	bd99b545c6787aa7fd0efb70987ec2e38bdd8469
SHA-256	090a9f47705fe00b60a7659ce926462943be2608e616359410fa0a3306646da4
Vhash	6de928d71a108a59bf4029f31e0980f9
SSDEEP	786432:1h+8sKFYYFIigfdwY8TCwCNUXgu1sYFrH2Ift1iY8MyKOEZJ/r0e8ihoZskoee2I:yTKFNuVwYHwC1u1926DlFT9KekNe2I
File type	Android
Magic	Zip archive data
File size	47.33 MB (49624136 bytes)
```
这里可以下载到 https://apk4k.fun/app/com.v2ray.v2fly
还有这里：
https://android-top.com/apk/com.v2ray.v2fly
看起来是同一个文件

**Comment by PassWall-OpenWrt** [comment]
下载软件请从可信网站下载，最好是官方网站，经由作者发布的可信地址下载。

v2rayNG 作者 github 地址 [https://github.com/2dust](url)
作者发布在 play商店 的软件 NG为免费
[https://play.google.com/store/apps/details?id=com.v2ray.v2fly](url)

该作者的另一个基于v2fly的Android工具（收费）
[https://play.google.com/store/apps/details?id=com.v2ray.ang](url)

**Comment by kslr** [comment]
我们没有发布过 android 文件
