### ISSUE TITLE
关于cloudflare.实现流量伪装的成功实践

### ISSUE THREAD

**Issue by judawu** [v2fly/discussion#17]
这段时间在网上发现有大神讲了CDN的原理，好奇的实践了一把，果然好使

大神给的方法：
> CDN识别流量是访问哪个网站的是根据请求头的Host来识别，所以这里要么host用我们的域名 ，要么我们伪装成我们的域名，这样都可以达到回源我们网站的请求。如果自己有域名也可以换自己的域名，域名也可以从第三方接入商cname

这里只给出V2ray客户端Config.json的代码：

`
 "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
//这里的地址可以是Cloudfare，或者你能找到的最优的Cloudfare的IP地址
            "address": "cloudflare.com", 
            "port": 443,
            "users": [
              {
                "id": "your UUID",   //你的UUID
                "alterId":  your alterid,  //你的额外ID
                "security": "auto"
              }
            ]
          }
        ],
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
//这个tlsSettings一定要有，不然貌似出现401 错误
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "your VPS address" //你的VPS域名地址xxx.xxx或者你的cloudflare. worker 转换的地址xxx.workers.dev"
        },
        "wsSettings": {
          "connectionReuse": true,
          "path": "your path",   //你的路径
          "headers": {
            "Host": "your VPS address" /你的VPS域名地址xxx.xxx或者你的cloudflare. worker 转换的地址xxx.workers.dev
          }
        }
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    }  
}
`

这只是Vmess的配置，V2rayN也是一样的，只要把地址改造cloudflare.com,伪装域名改成你的VPS域名地址就行

目前只测试Vmess的方式，Vless应该也可以实现相同的伪装

**Comment by GleenJi** [comment]
可以观察一下v2rayN-core，伪装域名那一栏填写自己的域名，那么vmess/vless+ws+tls(+cdn)对应的配置文件里tls setting会存在“serverName:你的域名”，ws setting会存在"Host:你的域名“
