### ISSUE TITLE
根据用户的源 IP 动态填入 clientIP

### ISSUE THREAD

**Issue by CalmLong** [v2fly/discussion#19]
假设本机 V2Ray 开个的任意门协议，然后监听 53 端口用来接收 DNS 查询的流量，假设本机 IP 是 192.168.1.1

但是目前 clientIp 只能设置一个，在 DNS 查询的时候起作用

假设我用另一台 IP 为 192.168.1.2 的机器 DNS 地址设置为 192.168.1.1

这时候 V2Ray 可以知道是 192.168.1.2 这台机器连接了，然后把 192.168.1.2 这个 IP 当作 clientIp 来用

v2fly/v2ray-core#169

@Loyalsoldier

**Comment by CalmLong** [comment]
@Vigilans

**Comment by kslr** [comment]
I’d be willing to review a PR if you want to contribute a fix.

**Comment by CalmLong** [comment]
那太好了，感谢大佬@kslr

**Comment by CalmLong** [comment]
抱歉，以我现在的能力不足以提交这个PR
