### ISSUE TITLE
关于AEAD与VLESS强制客户端与服务端版本一致性的一些疑惑

### ISSUE THREAD

**Issue by Rangtian** [v2fly/discussion#2]
启用AEAD与VLESS的话，版本不一致会导致客户端无法连接服务端？

我在VPS上搭了v2ray服务端，并分享给最亲近的几个人使用。如果强制要求版本一致，岂不是只能让所有人先同时更新客户端，然后我再去更新服务端？如果我先更新了服务端，那些尚未更新客户端的亲朋好友不就因为连不上服务端而无法更新客户端了么？

那些建机场的怎么办？不可能保证所有的客户端都能与服务端版本一致啊？

**Comment by RPRX** [comment]
AEAD 是 VMess 的，下个版本开始客户端 alterId 设为 0 才启用，目前 v4.26.0 及以后的版本的服务端都同时兼容 AEAD 和旧协议。

VLESS 是另一个协议了，测试期间要求客户端与服务端的 v2ray-core 均为最新版本，若不使用这个协议则该要求就是不存在的。

**Comment by Rangtian** [comment]
@rprx 感谢解答。

你提到 VLESS 是“测试期间要求客户端与服务端的 v2ray-core 均为最新版本”，是不是意味着正式发布后就不要求客户端与服务端一致了？

如果依旧要求一致，是不是意味着多客户端共享一个服务端的情况下，只能用旧协议？因为新协议客观上限制了多用户场景对 v2ray-core 的更新。

**Comment by Rangtian** [comment]
现在就有点难受。测了下速，目前VLESS也没比VMESS快。VLESS在正式发布后，是否依旧要求客户端服务端版本一致，也没个准确消息。如果有版本一致性这么严格的限制，我就直接换Trojan-Go了。

**Comment by RPRX** [comment]
1. 根据常识，正式版不会要求客户端服务端版本一致。实际上，测试版的 VLESS 都会被超长期支持。
2. “测了下速，目前VLESS也没比VMESS快”，建议看一下代码，VLESS 是 VMESS 的精简。
3. v2ray 和 trojan-go 都是免费的，想用哪个用哪个。不过我需要完成 VLESS 的先进性说明（
