### ISSUE TITLE
关于v2ray@.service

### ISSUE THREAD

**Issue by GleenJi** [v2fly/discussion#21]
小白问一下这两个v2ray.service和v2ray@.service有什么区别呢？我现在用的是4.28.2最新版本，v2ray和caddy都是亲自手动安装的，就是在/etc/systemd/system/下放置*.service文件时感觉v2ray@.service完全用不到啊，在执行指令systemctl daemon-reload   和   systemctl enable v2ray后，并没有提及到v2ray@.service这个文件，是不是这个文件没什么太大用处或者用不到？

**Comment by cloud-yu** [comment]
@.service是用来定制不同配置文件服务使用的.
默认情况下，v2ray.service使用默认的/usr/local/etc/v2ray/config.json
如果此时同目录下有另一个配置文件ws.json，想用使用这个配置文件启动服务，可以使用systemctl start v2ray@ws.service
此时就会用到@.service这个文件

**Comment by GleenJi** [comment]
> 
> 
> @.service是用来定制不同配置文件服务使用的.
> 默认情况下，v2ray.service使用默认的/usr/local/etc/v2ray/config.json
> 如果此时同目录下有另一个配置文件ws.json，想用使用这个配置文件启动服务，可以使用systemctl start [v2ray@ws.service](mailto:v2ray@ws.service)
> 此时就会用到@.service这个文件

感谢解答，意思就是：如果只用到一个config.json，那v2ray@.service就没什么用；
如果有多个v2ray配置文件（之间不同名），想用哪个配置文件进行启动v2ray，那就用这条命令“systemctl start v2ray@名字.service”来启动v2ray，此时就用到systemd/system/v2ray@.service了;
systemd/system/v2ray.service也可以说是v2ray的默认服务,因为一般我们用命令“systemctl start v2ray.service”启动v2ray;
还有v2ray.service和v2ray@.service是不是不能同时使用，

**Comment by cloud-yu** [comment]
可以一起用，只要引用的不是同一个配置文件就行，同一个配置文件会有端口占用
