### ISSUE TITLE
请问能否给v2ray-core添加Webhooks？以自动构建Docker镜像

### ISSUE THREAD

**Issue by shiwaimanong** [v2fly/discussion#25]
现在GitHub和Docker Hub都没有这种订阅发布自动触发的功能，如果使用GitHub的API的话则必须部署服务。

请问能否开放给v2ray-core添加Webhooks的申请？为需要关注发布情况，自动构建的功能提供支持。比如我的Docker Hub镜像创建了一个触发器：
```
https://hub.docker.com/api/build/v1/source/cd3abdd1-ae0b-4823-b131-d3e055a7a5d3/trigger/7d716dab-9116-4084-9f06-1f52fec5d31e/call/
```

需要在v2ray-core库的设置中添加一个Webhooks：
* Payload URL 填：`https://hub.docker.com/api/build/v1/source/cd3abdd1-ae0b-4823-b131-d3e055a7a5d3/trigger/7d716dab-9116-4084-9f06-1f52fec5d31e/call/`
* Which events would you like to trigger this webhook? 选：`Let me select individual events.`，并勾选：`Releases`
* Active 勾选

这样每次v2ray-core发布新版后Docker Hub镜像就会得到通知，自动进行构建。

**Comment by kslr** [comment]
有任何新的变化吗
