### ISSUE TITLE
vless的回落模式可以支持根据不同域名，回落到不同的端口吗

### ISSUE THREAD

**Issue by usgate** [v2fly/discussion#28]
因为vless开启回落伪装，443被占用。以前搭建其他的服务可以通过nginx/caddy通过不同域名反代出去 @rprx

**Comment by RPRX** [comment]
现在不可以，请用 Nginx SNI 分流。

**Comment by RPRX** [comment]
文档里完全没有写，一般就是不支持。由于类似问答反复出现，已在文档中补充此说明：

https://www.v2fly.org/config/protocols/vless.html#fallbackobject
