### ISSUE TITLE
systemd启动v2ray，使用confdir配置，服务启动失败

### ISSUE THREAD

**Issue by cloud-yu** [v2fly/discussion#29]
如下，使用v2ray@.service.d/目录增加20-usedir.conf，修改ExecStart为使用 -confdir选项，启动服务失败，
通过日志如下加粗处看到，v2ray程序选择了从STDIN获取配置文件，没有从目录获取配置文件。
目录内存放有00_log.json   03_routing.json  05_inbounds.json 06_outbounds.json
 

> systemctl status v2ray@ws
● v2ray@ws.service - V2Ray Service
     Loaded: loaded (/etc/systemd/system/v2ray@.service; disabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/v2ray@.service.d
             └─10-donot_touch_single_conf.conf, 20-usedir.conf
     Active: failed (Result: exit-code) since Thu 2020-10-01 01:10:05 CST; 3s ago
       Docs: https://www.v2fly.org/
    Process: 129035 **ExecStart=/usr/local/bin/v2ray -confdir /home/mistery/.local/share/v2ray/ws** (code=exited, status=23)
   Main PID: 129035 (code=exited, status=23)

Oct 01 01:10:04 vultr.guest systemd[1]: Started V2Ray Service.
Oct 01 01:10:05 vultr.guest v2ray[129035]: V2Ray 4.29.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 >
Oct 01 01:10:05 vultr.guest v2ray[129035]: A unified platform for anti-censorship.
**Oct 01 01:10:05 vultr.guest v2ray[129035]: 2020/10/01 01:10:05 Using config from STDIN**
Oct 01 01:10:05 vultr.guest v2ray[129035]: main: failed to read config files: [stdin:] > v2ray.com/core/main/json: fail>
Oct 01 01:10:05 vultr.guest v2ray[129035]: v2ctl> Read config:  stdin:
Oct 01 01:10:05 vultr.guest v2ray[129035]: v2ctl> v2ray.com/core/infra/conf/serial: failed to read config file > EOF > >
Oct 01 01:10:05 vultr.guest systemd[1]: v2ray@ws.service: Main process exited, code=exited, status=23/n/a
Oct 01 01:10:05 vultr.guest systemd[1]: v2ray@ws.service: Failed with result 'exit-code'.
lines 1-18/18 (END)

**Comment by cloud-yu** [comment]
闹了个乌龙，配置文件路径有一级文件夹没有设置other的read权限，导致nobody启动时无法读取配置文件

**Comment by CharlesShang** [comment]
经过你的提醒，我把 v2ray@.service 里面 nobody 改成了 root 后即可加入 systemctl 了
```
User=root # nobody
```
