### ISSUE TITLE
关于AES的提问

### ISSUE THREAD

**Issue by kl9800** [v2fly/discussion#3]
大佬好！
     我没看源码，所以想问一下，目前V2对于AES部分一律采用的是软加密吗？
     所以我有没有必要换一个支持AES的CPU的软路由？

**Comment by Rangtian** [comment]
支持硬加密的CPU能有效提升v2ray翻墙的速度。不过我个人觉得，除非你经常需要高速下载，否则没必要花上千元专门搞支持AES硬件加解密的软路由。一个100块的N1盒子做旁路由足矣，v2ray也能跑到270+Mbps

**Comment by kl9800** [comment]
谢谢！

**Comment by okudayukiko** [comment]
2015年以後的晶片都支援AES指令集。J1900是不支援AES指令集了。
