### ISSUE TITLE
关于xTLS加密数据流的疑问

### ISSUE THREAD

**Issue by Fhokud** [v2fly/discussion#32]
xTLS是把tls加密过的数据不再加密，可如果tls协商的加密算法的不同，

v2ray客户端和服务器协商aes128cfb，浏览器和网站服务器协商chacha20或其他算法。

这会一个tls连接上产生不同的加密算法流？
这是否会成为特征？

**Comment by RPRX** [comment]
不会，建议研究下 TLS 的传输格式。
