### ISSUE TITLE
最新的v2ray装好后json文件在哪里啊？

### ISSUE THREAD

**Issue by finch7** [v2fly/discussion#35]
最新的v2ray装好后json文件在哪里啊？
我在etc里面根本找不到v2ray文件夹，官网和其他论坛也没有相关信息

**Comment by SakuraChanNya** [comment]
在/usr/local/etc/v2ray

**Comment by hnliuzesen** [comment]
[https://github.com/v2fly/fhs-install-v2ray/blob/master/README.zh-Hans-CN.md](https://github.com/v2fly/fhs-install-v2ray/blob/master/README.zh-Hans-CN.md)
installed: /usr/local/bin/v2ray
installed: /usr/local/bin/v2ctl
installed: /usr/local/share/v2ray/geoip.dat
installed: /usr/local/share/v2ray/geosite.dat
installed: /usr/local/etc/v2ray/config.json
installed: /var/log/v2ray/
installed: /var/log/v2ray/access.log
installed: /var/log/v2ray/error.log
installed: /etc/systemd/system/v2ray.service
installed: /etc/systemd/system/v2ray@.service
