### ISSUE TITLE
direct mode无法相容origin mode

### ISSUE THREAD

**Issue by delphinuz** [v2fly/discussion#38]
測试了 2.3/2.4 preview版本，二端origin没问题，二端direct也没问题。

若server改为direct mode，client端使用origin mode，会出现

` [Warning] [3847769989] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: UID is not able to use xtls-rprx-origin`

若server改为origin，client端使用direct mode，会出现

`[Warning] [2099326943] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: UID is not able to use xtls-rprx-direct`

简单说就是互不相容，按作者的说法，direct mode应兼容origin mode.(或是我理解错误？)

**Comment by RPRX** [comment]
~~工作原理上兼容~~，但配置上故意不兼容。服务端应当能决定客户端的选择范围。

工作原理上也不完全兼容
