### ISSUE TITLE
Windows 能做服务器端吗？可以提供一份教程吗？

### ISSUE THREAD

**Issue by mtvktvcn** [v2fly/discussion#4]
Windows 能做服务器端吗？可以提供一份教程吗？

**Comment by PassWall-OpenWrt** [comment]
**V2Ray core是可以作为服务端也可以作为客户端的，作为哪个端取决于你的配置。**
可以用搜索引擎 搜索 **Windows2012搭建代理V2ray服务器端客户端64位系统**
利用v2rayN windows 端进行gui界面的配置 导出为服务器端配置 使用。

**Comment by usgate** [comment]
和linux一样的

**Comment by kslr** [comment]
请查阅 https://www.v2fly.org/
