### ISSUE TITLE
局域网内链式代理使用vless + TLS的问题

### ISSUE THREAD

**Issue by colazcy** [v2fly/discussion#40]
目前局域网内只有一台电脑A能够稳定的访问外网，但是局域网内的电脑之间互访是没有问题的。因此在A上搭建了一个socks5代理服务器，平时通过A访问国内网站没有问题。

没有A电脑的权限，因此无法在A电脑上搭建v2ray。我用的配置为VLESS +XTLS，请问有办法通过A来代理实现科学上网吗

即my computer ---> A ----> v2ray server

其中：
my computer ---> A，同在一个局域网内，走socks5代理
A ---> v2ray server，使用VLESS + XTLS

**Comment by kslr** [comment]
可以的，你只需要允许局域网设备连接
