### ISSUE TITLE
vless什么时候能支持链接分享

### ISSUE THREAD

**Issue by eightsheep67** [v2fly/discussion#43]

**Comment by yomnxkcs** [comment]
虽然我也希望v2fly团队快点把分享链接标准定下来，但是vless及xtls还在添功能（做加法）阶段，如果现在定下标准，很快又要修改，所以还是耐心点再等等吧。

**Comment by eightsheep67** [comment]
> 虽然我也希望v2fly团队快点把分享链接标准定下来，但是vless及xtls还在添功能（做加法）阶段，如果现在定下标准，很快又要修改，所以还是耐心点再等等吧。

原来如此，辛苦各位大佬的维护了！

**Comment by kslr** [comment]
将在成为正式版后推出
