### ISSUE TITLE
How update the V2ray? 更新地址被转移了，点击获取更新失败了。

### ISSUE THREAD

**Issue by icucuio** [v2fly/discussion#44]
I installed in openwrt. 
I can't get the update since you changed the update address. 
How to fixed? or how to install offline? 

![image](https://user-images.githubusercontent.com/69136587/95929142-de244680-0df5-11eb-9e6f-64a5262a39d9.png)
![image](https://user-images.githubusercontent.com/69136587/95929238-1035a880-0df6-11eb-8870-a4dd3fbf217b.png)

**Comment by ditele1** [comment]
![image](https://user-images.githubusercontent.com/63184839/95934225-f058b180-0e02-11eb-84b4-9f5c216b5da2.png)
修改这个文件里的配置
![image](https://user-images.githubusercontent.com/63184839/95934284-1a11d880-0e03-11eb-8cd1-cb451d7f2669.png)
将v2ray改为V2fly就可以了，我也是今天才搞定。
