### ISSUE TITLE
请教一下 v2ray 配置的设计问题

### ISSUE THREAD

**Issue by topmyself** [v2fly/discussion#48]
一般使用 v2ray 程序的时候，都是使用json 格式文件，v2ray 读取 json 数据后，还需要使用 v2ctl 转换成 protobuf 格式，然后再对应成程序的数据结构，请问这个设计的初衷是什么啊？中间转换还依赖 v2ctl，这个不太合理。

**Comment by kslr** [comment]
一开始是为了路由器优化的，现在已经剥离了v2ctl。

**Comment by kslr** [comment]
protobuf 是为了支持多种类型配置
