### ISSUE TITLE
增加一个反向tcp连接的出口outbounds类型

### ISSUE THREAD

**Issue by limaofu** [v2fly/discussion#5]
目前v2ray的outbounds出口方向都是当前结点作为客户端对目标发起一个连接，
我的想法是增加一个outbound方向的监听端口，让目标对我发起tcp连接，类似于内网穿透
这样就能让处于内网的设备也能作为代理。

**Comment by limaofu** [comment]
也就是说出口outbounds方向的连接不是由自己这个结点发起的，而是由目标（下一跳）结点发起的tcp连接。好处就是可以进行内网穿透。

**Comment by rurirei** [comment]
see `dokodemo-door`

**Comment by kslr** [comment]
I’d be willing to review a PR if you want to contribute a fix.
