### ISSUE TITLE
Connection problem for secends 

### ISSUE THREAD

**Issue by PayaMousavi** [v2fly/discussion#51]
Hey,
as i using v2ray for just myself there isn't any problem for connection but after 100 ~ 200 user with same UUID and config on vmess + ws+ tls it happens frequently for 5 ~ 10 secends internet disconnect but sill have down/up rate
the server is 8c with 20gb ram and only have one percent usage 
can anyone help me about this problem?

**Comment by kslr** [comment]
fixed
