### ISSUE TITLE
XTLS Flow

### ISSUE THREAD

**Issue by vVxiliVv** [v2fly/discussion#55]
I am a noobie when it comes to more advanced tls subjects and i can't find info about it with google.

What is xtls exactly and what is the difference between xtls-rprx-origin, xtls-rprx-origin-udp443.

i am tring to learn new things.

Thanks!

**Comment by RPRX** [comment]
https://www.v2fly.org/config/protocols/vless.html#xtls-%E9%BB%91%E7%A7%91%E6%8A%80

**Comment by vVxiliVv** [comment]
yeah i have read that multiple times with translate.
What is the difference between those two options, how does it changes the data flow or what does it even do?

**Comment by RPRX** [comment]
VLESS client will stop UDP/443 requests when using xtls-rprx-origin in order to stop QUIC, but will not stop these requests when using xtls-rprx-origin-udp443.

**Comment by vVxiliVv** [comment]
Thanks for the answer!
Why does this needed to be implemented?
So it does not really affect the encryption.
Also, when i configured quic, on 4.31.0 (server)
and with the latest v2rayng, nothing happened, logs showed nothing.

Wich stream is better, quic or tcp.
Quic uses udp as far as i know, can i use it with allowinsecure true? I have unlimiteddeezer data, and when i change the servername to api.deezer.com i have unlimited data.
I am tring to max out the throughtput of my server that is why i am asking.

Thank you for your time!

**Comment by RPRX** [comment]
Stopping QUIC means preventing apps like YouTube from choosing UDP QUIC rather than TCP TLS, which will make XTLS meaningless (as XTLS only works for TCP TLS above, not UDP QUIC over TCP).

**Comment by vVxiliVv** [comment]
Got my answer, thanks!
