### ISSUE TITLE
疑问: 协议头第18字节为什么不是版本号1?

### ISSUE THREAD

**Issue by k79e** [v2fly/discussion#58]
16 字节	X 字节	余下部分
认证信息	指令部分	数据部分

```
0000  fc 20 03 49 9a 40 7e c8  9b 15 c4 33 1f d4 0b 9e   . .I.@~. ...3....
0010  83 e2 f6 3d 1c 0f 65 41
```

这里是0x83 不是1啊

**Comment by RPRX** [comment]
VLESS 协议头第一个字节是版本号，目前是 0，第十八个字节是附加信息长度。

**Comment by RPRX** [comment]
（貌似你说的是 VMess）

**Comment by RPRX** [comment]
不管是 VMess 还是 VMessAEAD，指令部分 100% 是加密的，数据部分可选不加密（但仍有些多余计算）。

**Comment by k79e** [comment]
对的 我说的是vmess
vmess明文也是指令加密的?

原来是这样 那看来得解密下才成
