### ISSUE TITLE
既然有人提希望支持yaml格式，那么我也提:希望支持toml格式

### ISSUE THREAD

**Issue by ghost** [v2fly/discussion#62]
**toml明显比yaml简洁啊**

![tenor.gif](https://user-images.githubusercontent.com/30213081/97108580-7e893d80-1709-11eb-96e8-21c364245dd9.gif)

**Comment by k79e** [comment]
yaml搞不好缩进还会出问题 有时候要人命

**Comment by kslr** [comment]
I’d be willing to review a PR if you want to contribute a fix.
