### ISSUE TITLE
Reload v2ray config without restarting v2ray.

### ISSUE THREAD

**Issue by vVxiliVv** [v2fly/discussion#64]
First my setup:

When somone registers on my site, his/her info gets stored in mysql .> ShadowsocksR (python multiuser) starts a server automatically, under 1 process -> v2ray starts with  1 user on a new port with that shadowsocks server as outbound, 
With this i am able to achive: 
- speed limitation
- data qouta
- easly accesible qouta from mysql so my website can show data usage in realtime

what i would like to achieve:
Whenever somone registers, a script adds the new user to the inbound (vmess) and outbound (shadowsocks) to the server.json file and reloads the config.

The problem:
As far as i know, v2ray needs to be closed and run again to read the changes wich has been made to the config file, this drops the connections wich is bad.

Is it possbile to reload the server.json file without actually closing v2ray so users won't get dropped?

Thanks!

**Comment by kslr** [comment]
I’d be willing to review a PR if you want to contribute a fix.
