### ISSUE TITLE
vless+ws+caddy(tls)这个方案安全吗

### ISSUE THREAD

**Issue by usgate** [v2fly/discussion#7]
以前部署的vmess+ws+caddy(tls)，现在只把协议改变成vless，有没有安全问题，这种方式推荐吗

**Comment by usgate** [comment]
@rprx

**Comment by RPRX** [comment]
没有安全问题，但更推荐 https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-TLS-WS%20(recommended)

**Comment by usgate** [comment]
> 没有安全问题，但更推荐 https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-TLS-WS%20(recommended)

web服务器转发的方式，在伪装程度上应该比v2ray好吧，而且可以自动tls。
相对而言，以上推荐的方式是否是服务端压力更小，或者连接速度更快，还是更安全

**Comment by RPRX** [comment]
https://github.com/badO1a5A90/v2ray-doc/blob/master/v2ray%20speed%20test%20v4.27.2.md#vless%E5%88%86%E6%B5%81%E5%92%8Cnginx%E5%88%86%E6%B5%81%E6%80%A7%E8%83%BD%E7%9A%84%E5%AF%B9%E6%AF%94

**Comment by usgate** [comment]
> https://github.com/badO1a5A90/v2ray-doc/blob/master/v2ray%20speed%20test%20v4.27.2.md#vless%E5%88%86%E6%B5%81%E5%92%8Cnginx%E5%88%86%E6%B5%81%E6%80%A7%E8%83%BD%E7%9A%84%E5%AF%B9%E6%AF%94

我觉得对于能自己去部署v2ray的大多数人来说，性能的瓶颈并不在于服务端，需要跑满500M带宽的应用场景太少。测试两台服务器间的各个协议性能峰值对于多数人来说，意义并不大。

个人一般会用手机，路由器，pc上部署v2
对于手机，pc来说，无论什么协议，基本都可以跑满带宽，关注的更多是安全
对于68u这种老爷路由器来说就不一样了，测试用的美西gia，cpu性能直接限制了网速。ss，或者 vmess/vless 的裸 tcp/wc，在这台路由器上都可以跑到50M以上。但是打开tls后就不一样了，vmess+ws+tls只能跑12-14M，而vless+ws+tls能跑到18-20M
又测试了几次 vless+tcp+tls+回落，速度也在18-20M左右，并没有发生很大变化。vmess和vless在路由器速度的差距可能真的只是在于去掉了v2ray本身的加密。

显然的，对于性能好的设备，无论vmess，vless，还是tcp 或者 ws 回落还是web服务器分流，一般看视频，下载，浏览网页并没有太大的区别。

对于性能不好的设备，它的瓶颈在终端。服务器端部署vless+ws+web，又有什么不可以呢？
另外，相对于回落（现在我也没太搞明白到底是啥，我的理解它就是个分流+伪装的方式，用来代替web服务器的分流，伪装），我觉得web服务器，在墙看来它更像个web服务器

**Comment by rprx** [comment]
WS 是 1-RTT 的。

**Comment by rprx** [comment]
VLESS 前置可以为即将到来的 XTLS 做铺垫，需要的资源更少，比 SS 吞吐量更大。

**Comment by RPRX** [comment]
WS 是 1-RTT 的。VLESS 前置还可以为即将到来的 XTLS 做铺垫，消耗的资源更少，比 SS 吞吐量更大。

**Comment by usgate** [comment]
> WS 是 1-RTT 的。VLESS 前置还可以为即将到来的 XTLS 做铺垫，消耗的资源更少，比 SS 吞吐量更大。

现实情况是vless的tcp+tls，并没有比vless的ws+tls快，也许提升的是cpu或者内存消耗，但是真的感觉不到区别

**Comment by rprx** [comment]
> 现实情况是vless的tcp+tls，并没有比vless的ws+tls快，也许提升的是cpu或者内存消耗，但是真的感觉不到区别

少一层的确会减少些 CPU 些内存消耗，但 WS 不涉及加密，所以影响不大。影响最大的还是 1-RTT，WS 在传输真正的数据前要多一次往返。

**Comment by RPRX** [comment]
> 现实情况是vless的tcp+tls，并没有比vless的ws+tls快，也许提升的是cpu或者内存消耗，但是真的感觉不到区别

少一层的确会减少些 CPU 和内存消耗，但 WS 不涉及加密，所以影响不大。影响最大的还是 1-RTT，WS 在传输真正的数据前要多一次往返。

**Comment by usgate** [comment]
> > 现实情况是vless的tcp+tls，并没有比vless的ws+tls快，也许提升的是cpu或者内存消耗，但是真的感觉不到区别
> 
> 少一层的确会减少些 CPU 和内存消耗，但 WS 不涉及加密，所以影响不大。影响最大的还是 1-RTT，WS 在传输真正的数据前要多一次往返。

0-RTT还是1-RTT,其实实际体验并无差别。我也知道tcp+tls更好，但是在伪装方面，我还是觉得web服务器做的更彻底，其实这也在于个人对于安全和效率的平衡选择。
