### ISSUE TITLE
编译V2RAY的时候总是提示....(type *tls.Certificate) to type *qtls.Certificate

### ISSUE THREAD

**Issue by Tonkercke** [v2fly/discussion#83]
如题，把v2ray源代码放到openwrt下编译的时候总是提示下面的错误，并且提示需要go 1.14.

github.com/lucas-clemente/quic-go/internal/qtls
# github.com/lucas-clemente/quic-go/internal/qtls
pkg/mod/github.com/lucas-clemente/quic-go@v0.18.1/internal/qtls/qtls.go:79:25: cannot convert cert (type *tls.Certificate) to type *qtls.Certificate
note: module requires Go 1.14

Cleaning module download cache (golang/go#27455)

但是我已经安装了go 1.15.4的版本，使用go version检查go版本也会正常显示 go version go1.15.4 linux/amd64。
一开始认为是go没有安装正确，但是重装了linux系统，使用了很多安装go的方法，但是到编译v2ray的时候就报错。不知是哪里出了问题，希望有朋友能帮帮忙。

下面是我使用的系统情况：
openwrt的源代码是openwrt在gihub上的代码库，选择的版本是19.7.4
电脑系统是ubuntu 18.4的长期版
电脑已经处于全局代理，（软路由上的passwall设置的全局代理端口接到电脑上的）。

**Comment by kslr** [comment]
https://www.v2fly.org/developer/intro/compile.html

**Comment by kslr** [comment]
https://github.com/coolsnowwolf/lede
这里已经解决了，你参考一下
