### ISSUE TITLE
关于koolshare-v2ray for openwrt -更新失败

### ISSUE THREAD

**Issue by 007ssc** [v2fly/discussion#84]
**### 我查了下地址更改到V2FLY连接，无法自动更新。请问如何更新到新版本**
====================
【2020年11月15日 19:28:48】: 开始检查 v2ray 最新版本。。。
【2020年11月15日 19:28:49】: 当前版本：v4.28.2
【2020年11月15日 19:28:49】: 最新版本：v4.31.0
【2020年11月15日 19:28:49】: 准备升级到最新版本，开始下载
--2020-11-15 19:28:49--  https://github.com/v2ray/v2ray-core/releases/download/v4.31.0/v2ray-linux-64.zip
Resolving github.com... 13.229.188.59
Connecting to github.com|13.229.188.59|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-11-15 19:28:50 ERROR 404: Not Found.

【2020年11月15日 19:28:50】: 最新版本下载失败，请检查网络到github的连通后再试！

**Comment by Yochee** [comment]
脚本过时了，可以手动改，具体忘了...
koolshare上那个v2ray的UI已经很久没人维护了吧...年初就从官方商店下架了
建议换用一些维护中的openwrt luci app

**Comment by kslr** [comment]
大概你需要手动修改路径

**Comment by 007ssc** [comment]
那里更改更新路径
