### ISSUE TITLE
vless+xtls支持mux吗

### ISSUE THREAD

**Issue by flyhigherpi** [v2fly/discussion#87]
如题

**Comment by xqzr** [comment]
https://www.v2fly.org/config/protocols/vless.html#xtls-%E9%BB%91%E7%A7%91%E6%8A%80
注意事项
3.**不能开启 Mux**。XTLS 需要获得原始的数据流，所以原理上也不会支持 WebSocket、不适用于 VMess。此外，UDP over TCP 时，VLESS 不会开启 XTLS 的特殊功能。
