### ISSUE TITLE
api addInbound 的 InboundHandlerConfig怎么指定协议protocol？

### ISSUE THREAD

**Issue by zzxap** [v2fly/discussion#88]
inboxconfig := &core.InboundHandlerConfig{
		Tag: inboundTag,
		ReceiverSettings: serial.ToTypedMessage(&proxyman.ReceiverConfig{
			PortRange: net.SinglePortRange(80),
			Listen:    net.NewIPOrDomain(net.LocalHostIP),
		}),
		ProxySettings: serial.ToTypedMessage(&dokodemo.Config{
			Address:  net.NewIPOrDomain(dest.Address),
			Port:     uint32(dest.Port),
			Networks: []net.Network{net.Network_TCP},
		}),
	}

ReceiverSettings只有端口和ip  没办法指定协议吗？

**Comment by kslr** [comment]
请查阅  HandlerService 部分

**Comment by zzxap** [comment]
HandlerService  没有介绍代码的。只有简单的几行
HandlerService
一些对于入站出站代理进行修改的 API，可用的功能如下：

添加一个新的入站代理；
添加一个新的出站代理；
删除一个现有的入站代理；
删除一个现有的出站代理；
在一个入站代理中添加一个用户（仅支持 VMess、VLESS、Trojan）；
在一个入站代理中删除一个用户（仅支持 VMess、VLESS、Trojan）；

怎么指定protocol？
