### ISSUE TITLE
ReceiverSettings 和ProxySettings有什么区别？

### ISSUE THREAD

**Issue by zzxap** [v2fly/discussion#90]
Inbound: []*core.InboundHandlerConfig{
			{
				Tag: "d",
				ReceiverSettings: serial.ToTypedMessage(&proxyman.ReceiverConfig{
					PortRange: net.SinglePortRange(clientPort),
					Listen:    net.NewIPOrDomain(net.LocalHostIP),
				}),
				ProxySettings: serial.ToTypedMessage(&dokodemo.Config{
					Address:  net.NewIPOrDomain(dest.Address),
					Port:     uint32(dest.Port),
					Networks: []net.Network{net.Network_TCP},
				}),
			},

好难理解，端口和ip要怎么填

**Comment by kslr** [comment]
https://www.v2fly.org/config/outbounds.html?#proxysettingsobject
