### ISSUE TITLE
[feature request] IPv4流量重定向到IPv6

### ISSUE THREAD

**Issue by Sumire-Heanna** [v2fly/discussion#95]
需求概述：outbound处指定一个NAT64 Prefix (`a:b::/96`)，将所有经由此出口，目标为IPv4地址(`c.d.e.f`)的流量重定向到合成的NAT64 IPv6地址(`a:b::c.d.e.f`)
原因：
在仅支持IPv6的VPS上访问IPv4网络，需要以下的工作：
1.获得一个可用的NAT64 Prefix
2.获得与之匹配的DNS64地址，写入系统配置，将仅支持IPv4的**域名**解析到NAT64 IPv6地址
3.使用jool（已知）将系统所有目标地址为IPv4的流量重定向到NAT64地址

其中1，2解决起来比较方便，**3需要加载内核模块**，**而IPv6 only VPS多为非KVM架构**，**改动内核较为困难**，因此希望v2ray加入这一功能，拯救这些只支持IPv6的VPS

**Comment by kslr** [comment]
这个需求太小众了吧，不过如果你愿意实现的话，我也可以review
